server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: 1111


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # table info in console
    show-sql: true # table info in console
  mail:
    host: smtp.gmail.com
    port: 587
    # the proejct email!
    username: dexlee345@gmail.com
    # after 2단계인증, 발급 받은 app password
    password: zqnazeaeymknnsrw
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

# value in table
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE