server:
  port: 8080
  servlet:
    session:
      timeout: 5h

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # table info in console
    show-sql: true # table info in console

# value in table
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace